package lastproject;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIRAF
 */
public class frm_add_course extends javax.swing.JFrame {
     Connection con = null;
   PreparedStatement pst = null;
   ResultSet rs = null;

    /**
     * Creates new form f2
     */
    public frm_add_course() {
        initComponents();
        add_course_list();
        txt_edit_course_name.requestFocusInWindow();
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_edit_course_list_add = new javax.swing.JButton();
        btn_edit_course_list_clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_edit_course_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_edit_course_list_course_list = new javax.swing.JComboBox<>();
        btn_edit_course_list_delete = new javax.swing.JButton();
        btn_edit_course_list_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Record Management System Of ASD");
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);

        btn_edit_course_list_add.setBackground(new java.awt.Color(153, 153, 255));
        btn_edit_course_list_add.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_edit_course_list_add.setText("Add");
        btn_edit_course_list_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_course_list_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_course_list_addActionPerformed(evt);
            }
        });

        btn_edit_course_list_clear.setBackground(new java.awt.Color(153, 153, 255));
        btn_edit_course_list_clear.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_edit_course_list_clear.setText("Clear");
        btn_edit_course_list_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_course_list_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_course_list_clearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel1.setText("Course Name");

        txt_edit_course_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel3.setText("Add Course");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\t\tSri Lanka College of Technology - Maradana", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel2.setText("Delete Course");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel4.setText("Course Name ");

        cmb_edit_course_list_course_list.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        cmb_edit_course_list_course_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));

        btn_edit_course_list_delete.setBackground(new java.awt.Color(153, 153, 255));
        btn_edit_course_list_delete.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_edit_course_list_delete.setText("Delete");
        btn_edit_course_list_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_course_list_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_course_list_deleteActionPerformed(evt);
            }
        });

        btn_edit_course_list_refresh.setBackground(new java.awt.Color(153, 153, 255));
        btn_edit_course_list_refresh.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_edit_course_list_refresh.setText("Refresh");
        btn_edit_course_list_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_course_list_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_course_list_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_edit_course_list_add, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btn_edit_course_list_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_edit_course_name, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_edit_course_list_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btn_edit_course_list_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmb_edit_course_list_course_list, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_edit_course_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit_course_list_add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit_course_list_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 30, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_edit_course_list_course_list, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit_course_list_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit_course_list_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jSeparator1.getAccessibleContext().setAccessibleName("\t\t    Sri Lanka College of Technology");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_edit_course_list_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_course_list_addActionPerformed
        if(txt_edit_course_name.getText().isEmpty()==true){
        JOptionPane.showMessageDialog(null, "You have not entered the course name");
        txt_edit_course_name.requestFocusInWindow();
        }else{
        con = mysqlconnect.connectDB();
        try{
            String sql = "Insert into course_list (course_name) values(?)";
            pst = con.prepareStatement(sql);
            pst.setString(1,txt_edit_course_name.getText());
           
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Course added");
            
            cmb_edit_course_list_course_list.setSelectedIndex(0);
            txt_edit_course_name.setText("");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }finally{
            closeall();
        }
        add_course_list();
        txt_edit_course_name.requestFocusInWindow();
        
   
        
        
        }
    }//GEN-LAST:event_btn_edit_course_list_addActionPerformed

    private void btn_edit_course_list_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_course_list_clearActionPerformed
     txt_edit_course_name.setText("");
     txt_edit_course_name.requestFocusInWindow();
    }//GEN-LAST:event_btn_edit_course_list_clearActionPerformed

    private void btn_edit_course_list_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_course_list_refreshActionPerformed
        add_course_list();
        cmb_edit_course_list_course_list.setSelectedIndex(0);
    }//GEN-LAST:event_btn_edit_course_list_refreshActionPerformed

    private void btn_edit_course_list_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_course_list_deleteActionPerformed
        int choice=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this course","Delete course",JOptionPane.YES_NO_OPTION);
if(choice==0){
        con = mysqlconnect.connectDB();
        try{
            String sql = "delete from course_list where course_name=?";
            pst = con.prepareStatement(sql);
            pst.setString(1,cmb_edit_course_list_course_list.getSelectedItem().toString());
            
       
            pst.execute();
            JOptionPane.showMessageDialog(null,"Course  Deleted");
           
            btn_edit_course_list_refresh.doClick();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }finally{
            closeall();
        }
}   
    }//GEN-LAST:event_btn_edit_course_list_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_add_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_add_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_add_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_add_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_add_course().setVisible(true);
            }
        });
    }
        public void add_course_list(){
        con = mysqlconnect.connectDB();
        try{
            String sql = "select * from course_list";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String course_name = rs.getString("course_name");
                cmb_edit_course_list_course_list.addItem(course_name);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
                    }
        finally{
        closeall();
        }
        
    }
            public void closeall(){
try{
    
    rs.close();
    pst.close();
    con.close();
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit_course_list_add;
    private javax.swing.JButton btn_edit_course_list_clear;
    private javax.swing.JButton btn_edit_course_list_delete;
    private javax.swing.JButton btn_edit_course_list_refresh;
    private javax.swing.JComboBox<String> cmb_edit_course_list_course_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_edit_course_name;
    // End of variables declaration//GEN-END:variables
 public void seticon(){
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_Course_48px_1.png")));
 }
}
