/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lastproject;

import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author SHIRAF
 */
public class frm_add_centre extends javax.swing.JFrame {
     Connection con = null;
   PreparedStatement pst = null;
   ResultSet rs = null;

    /**
     * Creates new form f1
     */
    public frm_add_centre() {
     
        initComponents();
         dislist();
         dislist_delete();
         seticon();
            cmb_delete_center_district.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange()==ItemEvent.SELECTED){
                   
                    
                         cmb_delete_center_name.removeAllItems();
                    show_delete_cent();
            }
            }
        });
    
                     }
        public void show_delete_cent(){
        
                con=mysqlconnect.connectDB();
        try{
            String sql = "select * from centre_list where district = ?";
            pst=con.prepareStatement(sql);
            pst.setString(1,cmb_delete_center_district.getSelectedItem().toString());
            rs = pst.executeQuery();
            while(rs.next()){
            String cent = rs.getString("centre");
            cmb_delete_center_name.addItem(cent);}

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            
           closeall();
        }
        
    }
    public void dislist(){
        con = mysqlconnect.connectDB();
        try{
            String sql = "select * from district_list";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String dis = rs.getString("district_name");
                cmb_dislist.addItem(dis);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
                    }
        finally{
        closeall();
        }
    }
    public void dislist_delete(){
             con = mysqlconnect.connectDB();
        try{
            String sql = "select * from district_list";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String dis = rs.getString("district_name");
                cmb_delete_center_district.addItem(dis);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
                    }
        finally{
        closeall();
        }
        
    }
        public void closeall(){
try{
    
    rs.close();
    pst.close();
    con.close();
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmb_delete_center_district = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_delete_center_name = new javax.swing.JComboBox();
        btn_delete_center = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_clear_new_centre = new javax.swing.JButton();
        cmb_dislist = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_add_new_centre = new javax.swing.JButton();
        txt_centre_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Record Management System Of ASD");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel4.setText("Delete center");

        cmb_delete_center_district.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        cmb_delete_center_district.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select District" }));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel5.setText("District");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel6.setText("Center ");

        cmb_delete_center_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        cmb_delete_center_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_delete_center_nameActionPerformed(evt);
            }
        });

        btn_delete_center.setBackground(new java.awt.Color(153, 153, 255));
        btn_delete_center.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_delete_center.setText("Delete");
        btn_delete_center.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_centerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_delete_center, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_delete_center_district, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_delete_center_name, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_delete_center_district, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_delete_center_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btn_delete_center, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Center", jPanel3);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setAutoscrolls(true);

        btn_clear_new_centre.setBackground(new java.awt.Color(153, 153, 255));
        btn_clear_new_centre.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_clear_new_centre.setText("Clear");
        btn_clear_new_centre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_new_centreActionPerformed(evt);
            }
        });

        cmb_dislist.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel1.setText("Center");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel2.setText("District");

        btn_add_new_centre.setBackground(new java.awt.Color(153, 153, 255));
        btn_add_new_centre.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_add_new_centre.setText("ADD");
        btn_add_new_centre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_new_centreActionPerformed(evt);
            }
        });

        txt_centre_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel3.setText("Add Center");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_add_new_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btn_clear_new_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_dislist, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_centre_name, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_dislist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_centre_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear_new_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add_new_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Center", jPanel1);

        getContentPane().add(jTabbedPane1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_new_centreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_new_centreActionPerformed
if(txt_centre_name.getText().isEmpty()==true){
    JOptionPane.showMessageDialog(null,"You have not entered the center name");
    txt_centre_name.requestFocusInWindow();
}else{
        
        con = mysqlconnect.connectDB();
        try{
            String sql = "Insert into centre_list (district,centre) values(?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1,cmb_dislist.getSelectedItem().toString());
            pst.setString(2, txt_centre_name.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Centre added");
            txt_centre_name.setText("");
            cmb_dislist.setSelectedIndex(0);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }finally{
            closeall();
        }
        panel_staff.cmb_district.setSelectedIndex(0);
        
  

       
}
// TODO add your handling code here:
    }//GEN-LAST:event_btn_add_new_centreActionPerformed

    private void btn_clear_new_centreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_new_centreActionPerformed
txt_centre_name.setText("");
cmb_dislist.setSelectedIndex(0);
txt_centre_name.requestFocusInWindow();// TODO add your handling code here:
    }//GEN-LAST:event_btn_clear_new_centreActionPerformed

    private void btn_delete_centerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_centerActionPerformed
int choice=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this center","Delete center",JOptionPane.YES_NO_OPTION);
if(choice==0){
        con = mysqlconnect.connectDB();
        try{
            String sql = "delete from centre_list where district=? and centre=?";
            pst = con.prepareStatement(sql);
            pst.setString(1,cmb_delete_center_district.getSelectedItem().toString());
            pst.setString(2, cmb_delete_center_name.getSelectedItem().toString());
       
            pst.execute();
            JOptionPane.showMessageDialog(null,"Center  Deleted");
            cmb_delete_center_district.setSelectedIndex(0);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }finally{
            closeall();
        }
        panel_staff.cmb_district.setSelectedIndex(0);
        
}        // TODO add your handling code here:
    }//GEN-LAST:event_btn_delete_centerActionPerformed

    private void cmb_delete_center_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_delete_center_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_delete_center_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_add_centre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_add_centre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_add_centre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_add_centre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_add_centre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_new_centre;
    private javax.swing.JButton btn_clear_new_centre;
    private javax.swing.JButton btn_delete_center;
    private javax.swing.JComboBox cmb_delete_center_district;
    private javax.swing.JComboBox cmb_delete_center_name;
    private javax.swing.JComboBox cmb_dislist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_centre_name;
    // End of variables declaration//GEN-END:variables
 public void seticon(){
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_Course_48px_1.png")));
 }
}
