/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lastproject;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SHIRAF
 */
public class panel_train extends javax.swing.JPanel {
    Connection con = null;
   PreparedStatement pst = null;
   ResultSet rs = null;

    /**
     * Creates new form panel_train
     */
    public panel_train() {
        initComponents();
        updatetable();
    }
    public void updatetable(){
        con=mysqlconnect.connectDB();
     try{
         String sql = "select p_id as Programme_ID,p_name as Programme_Name,p_duration as 'Programme_Duration(Days)' from training_programme";
         pst=con.prepareStatement(sql);
         rs= pst.executeQuery();
         table_train.setModel(DbUtils.resultSetToTableModel(rs));
         
         
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
     finally{
     closeall();
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        txt_duration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_pname = new javax.swing.JTextField();
        txt_pid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_train_clear = new javax.swing.JButton();
        btn_train_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_train = new javax.swing.JTable();
        btn_train_delete = new javax.swing.JButton();
        btn_train_update = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel13.setText("Days");

        txt_duration.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        txt_duration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_durationKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel12.setText("Duration");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel11.setText("Programme Name");

        txt_pname.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        txt_pname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pnameKeyPressed(evt);
            }
        });

        txt_pid.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        txt_pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pidActionPerformed(evt);
            }
        });
        txt_pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pidKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel9.setText("Programme ID");

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel14.setText("Training Programmes");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        btn_train_clear.setBackground(new java.awt.Color(153, 153, 255));
        btn_train_clear.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_train_clear.setText("Clear");
        btn_train_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_train_clearActionPerformed(evt);
            }
        });

        btn_train_add.setBackground(new java.awt.Color(153, 153, 255));
        btn_train_add.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_train_add.setText("Save");
        btn_train_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_train_addActionPerformed(evt);
            }
        });

        table_train.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Programme ID", "Programme Name", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_train.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_trainMouseClicked(evt);
            }
        });
        table_train.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_trainKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_train);

        btn_train_delete.setBackground(new java.awt.Color(153, 153, 255));
        btn_train_delete.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_train_delete.setText("Delete");
        btn_train_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_train_deleteActionPerformed(evt);
            }
        });

        btn_train_update.setBackground(new java.awt.Color(153, 153, 255));
        btn_train_update.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_train_update.setText("Update");
        btn_train_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_train_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_train_add, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_train_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btn_train_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btn_train_update, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_pname, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_train_add, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_train_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_train_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_train_update, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_train_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_train_clearActionPerformed
        txt_pid.setText(null);
        txt_pname.setText(null);
        txt_duration.setText(null);
        txt_pid.requestFocusInWindow();// TODO add your handling code here:
    }//GEN-LAST:event_btn_train_clearActionPerformed

    private void btn_train_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_train_addActionPerformed
        if(checkempty()){
        JOptionPane.showMessageDialog(null, "You have not entered the Programme ID or Programme Name");
        txt_pid.requestFocusInWindow();}
        else{
               
        
        con = mysqlconnect.connectDB();
        try{
            String sql = "Insert into training_programme (p_id,p_name,p_duration) values(?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setString(1,txt_pid.getText());
            pst.setString(2, txt_pname.getText());
            pst.setString(3,txt_duration.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Programme added");
            txt_pid.setText("");
            txt_pname.setText("");
            txt_duration.setText("");
            txt_pid.requestFocusInWindow();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data not inserted");

        }finally{
            closeall();
        }updatetable();
        }
    }//GEN-LAST:event_btn_train_addActionPerformed

    private void txt_pidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pidKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER){
    txt_pname.requestFocusInWindow();
}        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pidKeyPressed

    private void txt_pnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pnameKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER){
    txt_duration.requestFocusInWindow();
}        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pnameKeyPressed

    private void txt_durationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_durationKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER){
    btn_train_add.doClick();
}        // TODO add your handling code here:
    }//GEN-LAST:event_txt_durationKeyPressed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void table_trainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_trainMouseClicked
       con = mysqlconnect.connectDB();
        int row = table_train.getSelectedRow();
       String table_click = (table_train.getModel().getValueAt(row,0).toString());
       try{
           String sql = "select * from training_programme where p_id = '"+table_click+"'";
           pst = con.prepareStatement(sql);
           rs = pst.executeQuery();
           if(rs.next()){
               String add_pid = rs.getString("p_id");
               txt_pid.setText(add_pid);
               String add_pname = rs.getString("p_name");
               txt_pname.setText(add_pname);
               String add_pduration = rs.getString("p_duration");
               txt_duration.setText(add_pduration);
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       finally{
           closeall();
       }
    }//GEN-LAST:event_table_trainMouseClicked

    private void btn_train_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_train_deleteActionPerformed
   if(checkempty()){
        JOptionPane.showMessageDialog(null, "No Programme Selected");
        txt_pid.requestFocusInWindow();}
   else{
       int choice=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this programme","Delete programme",JOptionPane.YES_NO_OPTION);
       if(choice==0){
        con = mysqlconnect.connectDB();
        try{
            String sql = "delete from training_programme where p_id=?";
            pst = con.prepareStatement(sql);
            pst.setString(1,txt_pid.getText());
       
            pst.execute();
            JOptionPane.showMessageDialog(null,"Programme Deleted");
            txt_pid.setText("");
            txt_pname.setText("");
            txt_duration.setText("");
            txt_pid.requestFocusInWindow();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Details not deleted");

        }finally{
            closeall();
        }updatetable();
   }
   }// TODO add your handling code here:
    }//GEN-LAST:event_btn_train_deleteActionPerformed

    private void btn_train_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_train_updateActionPerformed
       if(checkempty()){
        JOptionPane.showMessageDialog(null, "No Programme Selected");
        txt_pid.requestFocusInWindow();}
       else{
           int choice = JOptionPane.showConfirmDialog(null,"Are you sure you want to change details","Update Details",JOptionPane.YES_NO_OPTION);
           if(choice==0){
        con = mysqlconnect.connectDB();
       try{
           String sql = "update training_programme set p_name=? , p_duration=? where p_id=?";
           pst = con.prepareStatement(sql);
           pst.setString(1, txt_pname.getText());
           pst.setString(2, txt_duration.getText());
           pst.setString(3,txt_pid.getText());
           pst.execute();
           JOptionPane.showMessageDialog(null,"Details Updated");
            txt_pid.setText("");
            txt_pname.setText("");
            txt_duration.setText("");
           
           txt_pid.requestFocusInWindow();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Details not updated");
       }finally{
           closeall();
           
       }updatetable();}
       }
    }//GEN-LAST:event_btn_train_updateActionPerformed

    private void table_trainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_trainKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN ){
                 con = mysqlconnect.connectDB();
        int row = table_train.getSelectedRow();
       String table_click = (table_train.getModel().getValueAt(row,0).toString());
       try{
           String sql = "select * from training_programme where p_id = '"+table_click+"'";
           pst = con.prepareStatement(sql);
           rs = pst.executeQuery();
           if(rs.next()){
               String add_pid = rs.getString("p_id");
               txt_pid.setText(add_pid);
               String add_pname = rs.getString("p_name");
               txt_pname.setText(add_pname);
               String add_pduration = rs.getString("p_duration");
               txt_duration.setText(add_pduration);
           }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       finally{
           closeall();
       }
           
}
    }//GEN-LAST:event_table_trainKeyReleased

    private void txt_pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pidActionPerformed
public void closeall(){
    try{
         rs.close();
    pst.close();
    con.close();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);

            }
            
}
boolean checkempty(){
    if(txt_pid.getText().isEmpty()==true || txt_pname.getText().isEmpty()==true){
       return true;}
       else{
               return false;
               }
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_train_add;
    private javax.swing.JButton btn_train_clear;
    private javax.swing.JButton btn_train_delete;
    private javax.swing.JButton btn_train_update;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_train;
    private javax.swing.JTextField txt_duration;
    private javax.swing.JTextField txt_pid;
    private javax.swing.JTextField txt_pname;
    // End of variables declaration//GEN-END:variables
}
