/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lastproject;

import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author SHIRAF
 */
public class panel_staff extends javax.swing.JPanel {
    Connection con = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   
   ResultSet search_rs = null;
   PreparedStatement search_pst = null;
   Connection search_con = null;
   Boolean change_academic= false;
   

    /**
     * Creates new form panel_staff
     */
    public panel_staff() {
        initComponents();
        
        
        adddistrict();
        add_course_list_staff();
        
        cmb_district.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange()==ItemEvent.SELECTED){
                   
                    
                         cmb_center.removeAllItems();
                    showcent();
            }
            }
        });
        cmb_aca.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
              if(e.getStateChange()==ItemEvent.SELECTED){
                  if(cmb_aca.getSelectedIndex()==1){
                      cmb_course.setEnabled(false);
                  }else{
                      cmb_course.setEnabled(true);
                  }
              }
            }
        });
        }
                
                
    public void adddistrict(){
                con = mysqlconnect.connectDB();
        try{
            String sql = "select * from district_list";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String dis = rs.getString("district_name");
                cmb_district.addItem(dis);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
                    }
        finally{
        closeall();
        }
        
    }
    public void add_course_list_staff(){
        
        con = mysqlconnect.connectDB();
        try{
            String sql = "select * from course_list";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String course_name = rs.getString("course_name");
                cmb_course.addItem(course_name);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
                    }
        finally{
        closeall();
        }
        
    }
    public void showcent(){
        
                con=mysqlconnect.connectDB();
        try{
            String sql = "select * from centre_list where district = ?";
            pst=con.prepareStatement(sql);
            pst.setString(1,cmb_district.getSelectedItem().toString());
            rs = pst.executeQuery();
            while(rs.next()){
            String cent = rs.getString("centre");
            cmb_center.addItem(cent);}

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            
           closeall();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_epf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_district = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmb_center = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmb_course = new javax.swing.JComboBox<>();
        txt_tel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_addstaff = new javax.swing.JButton();
        btn_staff_clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmb_aca = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmb_stype = new javax.swing.JComboBox<>();
        btn_add_centre = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_staff_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_delete_staff = new javax.swing.JButton();
        btn_update_staff = new javax.swing.JButton();
        btn_edit_course_list = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        btn_attach_staff_image = new javax.swing.JButton();
        btn_staff_remove_image = new javax.swing.JButton();
        btn_refresh_course_list = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_status = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 204, 255));
        setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel1.setText("Staff Members");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel2.setText("NIC");

        txt_nic.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nicKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nicKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel3.setText("Name");

        txt_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nameKeyPressed(evt);
            }
        });

        txt_epf.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_epf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_epfFocusLost(evt);
            }
        });
        txt_epf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_epfKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel4.setText("EPF No");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel5.setText("District");

        cmb_district.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmb_district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select District" }));
        cmb_district.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_districtActionPerformed(evt);
            }
        });
        cmb_district.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_districtKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel6.setText("Center");

        cmb_center.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmb_center.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Centre" }));
        cmb_center.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_centerKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel7.setText("Course");

        cmb_course.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmb_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        cmb_course.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_courseKeyPressed(evt);
            }
        });

        txt_tel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_tel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_telFocusLost(evt);
            }
        });
        txt_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel8.setText("Telephone No");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel9.setText("E-mail ");

        txt_email.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        btn_addstaff.setBackground(new java.awt.Color(153, 153, 255));
        btn_addstaff.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_addstaff.setText("Save");
        btn_addstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addstaffActionPerformed(evt);
            }
        });

        btn_staff_clear.setBackground(new java.awt.Color(153, 153, 255));
        btn_staff_clear.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_staff_clear.setText("Clear");
        btn_staff_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staff_clearActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel10.setText("Academic Status");

        cmb_aca.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmb_aca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Non - Academic" }));
        cmb_aca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_acaKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel11.setText("Service Type");

        cmb_stype.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmb_stype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanet", "Contract basis" }));
        cmb_stype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_stypeKeyPressed(evt);
            }
        });

        btn_add_centre.setBackground(new java.awt.Color(153, 153, 255));
        btn_add_centre.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_add_centre.setText("Edit Centers");
        btn_add_centre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_centreActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel12.setText("Search");

        txt_staff_search.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_staff_search.setText(".....NIC.....");
        txt_staff_search.setToolTipText("Enter the NIC");
        txt_staff_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_staff_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_staff_searchKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jButton1.setText("Assign completed programs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_delete_staff.setBackground(new java.awt.Color(153, 153, 255));
        btn_delete_staff.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_delete_staff.setText("Delete");
        btn_delete_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_staffActionPerformed(evt);
            }
        });

        btn_update_staff.setBackground(new java.awt.Color(153, 153, 255));
        btn_update_staff.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_update_staff.setText("Update");
        btn_update_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_staffActionPerformed(evt);
            }
        });

        btn_edit_course_list.setBackground(new java.awt.Color(153, 153, 255));
        btn_edit_course_list.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_edit_course_list.setText("Edit Course List");
        btn_edit_course_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_course_listActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel13.setText("Gender");

        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });

        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_attach_staff_image.setBackground(new java.awt.Color(153, 153, 255));
        btn_attach_staff_image.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_attach_staff_image.setText("Attach");
        btn_attach_staff_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attach_staff_imageActionPerformed(evt);
            }
        });

        btn_staff_remove_image.setBackground(new java.awt.Color(153, 153, 255));
        btn_staff_remove_image.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_staff_remove_image.setText("Remove  Image");
        btn_staff_remove_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_staff_remove_imageActionPerformed(evt);
            }
        });

        btn_refresh_course_list.setBackground(new java.awt.Color(153, 153, 255));
        btn_refresh_course_list.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_refresh_course_list.setText("Refresh");
        btn_refresh_course_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_course_listActionPerformed(evt);
            }
        });

        txt_status.setEditable(false);
        txt_status.setColumns(20);
        txt_status.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_status.setRows(5);
        txt_status.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_status);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel14.setText("Status");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\t\tSri Lanka College of Technology - Maradana", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        jSeparator1.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_email)
                                    .addComponent(cmb_stype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_tel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_staff_search, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)
                                        .addComponent(btn_staff_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_addstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(97, 97, 97)
                                        .addComponent(btn_delete_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_update_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmb_center, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_add_centre))
                                    .addComponent(cmb_aca, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_district, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_refresh_course_list)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_edit_course_list, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_course, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(r_male)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(r_female))
                                        .addComponent(txt_epf, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(btn_attach_staff_image, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_staff_remove_image))
                        .addGap(148, 148, 148))))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_staff_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_staff_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_epf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(r_male)
                                    .addComponent(r_female)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_district, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_add_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmb_center, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_aca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_attach_staff_image, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btn_staff_remove_image, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_course, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_refresh_course_list, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit_course_list, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_stype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_addstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );

        jSeparator1.getAccessibleContext().setAccessibleName("\t\tSri Lanka College of Technology - Maradana");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addstaffActionPerformed
 
        txt_status.setText("");
        boolean something_wrong = false;
        if(checkempty()){
    JOptionPane.showMessageDialog(null," You have not entered the name or NIC no of staff member");
    txt_nic.requestFocusInWindow();
}else{   
    con = mysqlconnect.connectDB();
try{
    String sql = "insert into staff_member (s_nic,s_name,s_epf,s_district,s_center,s_tel,s_email,s_type,s_ac_status,gender,image) values(?,?,?,?,?,?,?,?,?,?,?)";
    pst = con.prepareStatement(sql);
    pst.setString(1, txt_nic.getText());
    pst.setString(2,txt_name.getText());
    pst.setString(3, txt_epf.getText());
    pst.setString(4,cmb_district.getSelectedItem().toString());
    pst.setString(5,cmb_center.getSelectedItem().toString());
    pst.setString(6, txt_tel.getText());
    pst.setString(7, txt_email.getText());
    pst.setString(8,cmb_stype.getSelectedItem().toString() );
    pst.setString(9,cmb_aca.getSelectedItem().toString());
    pst.setString(10, gender);
    pst.setBytes(11, person_image);
    pst.execute();
//    JOptionPane.showMessageDialog(null,"Staff member addded");
    txt_status.setText(txt_nic.getText()+ " Added  as a staff member\n" );
    
}catch(Exception e ){
     something_wrong = true;
    JOptionPane.showMessageDialog(null, "Data not inserted");
}finally{
            closeall();
            }
if(cmb_aca.getSelectedIndex()==0){
    addacademic();
}
    else{
          nonacademic();
            }
if(something_wrong == false){
select_train_program stp = new select_train_program();
stp.setVisible(true);
}
}


    
    }
    {
    }//GEN-LAST:event_btn_addstaffActionPerformed

    private void txt_nicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nicKeyPressed
if(evt.getKeyCode()== KeyEvent.VK_ENTER){
    txt_name.requestFocusInWindow();
}
    }//GEN-LAST:event_txt_nicKeyPressed

    private void txt_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyPressed
if(evt.getKeyCode()== KeyEvent.VK_ENTER){
   txt_epf.requestFocusInWindow();
}        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameKeyPressed

    private void txt_epfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_epfKeyPressed
if(evt.getKeyCode()== KeyEvent.VK_ENTER){
    cmb_district.requestFocusInWindow();
}        // TODO add your handling code here:
    }//GEN-LAST:event_txt_epfKeyPressed

    private void cmb_districtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_districtKeyPressed
if(evt.getKeyCode()== KeyEvent.VK_ENTER){
    cmb_center.requestFocusInWindow();
}        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_districtKeyPressed

    private void btn_staff_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staff_clearActionPerformed
txt_nic.requestFocusInWindow();
txt_name.setText("");
txt_nic.setText("");
txt_epf.setText("");
txt_email.setText("");
txt_tel.setText("");
cmb_district.setSelectedIndex(0);
cmb_course.setSelectedIndex(0);
cmb_stype.setSelectedIndex(0);
cmb_aca.setSelectedIndex(0);
txt_staff_search.setText("");
r_female.setSelected(false);
r_male.setSelected(false);
img.setIcon(null);
txt_status.setText("");
txt_status.setText("All Cleared");


    }//GEN-LAST:event_btn_staff_clearActionPerformed

    private void cmb_centerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_centerKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
    cmb_aca.requestFocusInWindow();
}  
    }//GEN-LAST:event_cmb_centerKeyPressed

    private void cmb_acaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_acaKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER){
    cmb_course.requestFocusInWindow();
}  
    }//GEN-LAST:event_cmb_acaKeyPressed

    private void cmb_courseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_courseKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
   cmb_stype.requestFocusInWindow();
}  
    }//GEN-LAST:event_cmb_courseKeyPressed

    private void cmb_stypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_stypeKeyPressed
           if(evt.getKeyCode()== KeyEvent.VK_ENTER){
   txt_tel.requestFocusInWindow();
}  
    }//GEN-LAST:event_cmb_stypeKeyPressed

    private void txt_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyPressed
             if(evt.getKeyCode()== KeyEvent.VK_ENTER){
   txt_email.requestFocusInWindow();
}  
    }//GEN-LAST:event_txt_telKeyPressed

    private void btn_add_centreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_centreActionPerformed
frm_add_centre add_centre = new frm_add_centre();
add_centre.setVisible(true);



    }//GEN-LAST:event_btn_add_centreActionPerformed

    private void txt_staff_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_staff_searchKeyReleased
     
        search_con = mysqlconnect.connectDB(); 
     
      try{
          String sql = "SELECT * FROM staff_member LEFT OUTER JOIN academic ON staff_member.s_nic = academic.s_nic LEFT OUTER JOIN non_academic ON staff_member.s_nic = non_academic.s_nic WHERE staff_member.s_nic = ?";
          
          search_pst = search_con.prepareStatement(sql);
          search_pst.setString(1,txt_staff_search.getText());
          search_rs = search_pst.executeQuery();
         
          if(search_rs.next()){
          String s_nic = search_rs.getString("s_nic");
          txt_nic.setText(s_nic);
          String s_name = search_rs.getString("s_name");
          txt_name.setText(s_name);
          String s_epf = search_rs.getString("s_epf");
          txt_epf.setText(s_epf);
              
          String s_ac_status = search_rs.getString("s_ac_status");
          cmb_aca.setSelectedItem(s_ac_status);
          String s_type = search_rs.getString("s_type");
          cmb_stype.setSelectedItem(s_type);
          String s_tel = search_rs.getString("s_tel");
          txt_tel.setText(s_tel);
          String s_email = search_rs.getString("s_email");
          txt_email.setText(s_email);
           
          String s_district = search_rs.getString("s_district");
          cmb_district.setSelectedItem(s_district);
          
            String s_center = search_rs.getString("s_center");
         cmb_center.setSelectedItem(s_center);
         
         String ins_course = search_rs.getString("ins_course");
         cmb_course.setSelectedItem(ins_course);
         
         String get_gender = search_rs.getString("gender");
         if(get_gender.equals("Male")){
             gender = "Male";
             r_male.setSelected(true);
             r_female.setSelected(false);
             
         }
         else if(get_gender.equals("Female")){
             gender = "Female";
             r_female.setSelected(true);
             r_male.setSelected(false);
         }else{
              r_female.setSelected(false);
             r_male.setSelected(false);   
         }  
         byte[] image = search_rs.getBytes("image");
         if(image == null){
//             JOptionPane.showMessageDialog(null,"No image");
         }else{
       
          
         ImageIcon imageicon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getHeight(), img.getWidth(), Image.SCALE_DEFAULT));
         img.setIcon(imageicon);}
        
          }else{
              clear_when_no_records();
//              JOptionPane.showMessageDialog(null,"No records found");
          } 
      }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
      } 
      finally{
         
          try{
    
    search_rs.close();
    search_pst.close();
    search_con.close();
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
      }
    }//GEN-LAST:event_txt_staff_searchKeyReleased
public void clear_when_no_records(){
    
txt_name.setText("");
txt_nic.setText("");
txt_epf.setText("");
txt_email.setText("");
txt_tel.setText("");
cmb_district.setSelectedIndex(0);
cmb_course.setSelectedIndex(0);
cmb_stype.setSelectedIndex(0);
cmb_aca.setSelectedIndex(0);

r_female.setSelected(false);
r_male.setSelected(false);
img.setIcon(null);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(check_nic()){
        select_train_program stp = new select_train_program();
stp.setVisible(true);
}else{
    JOptionPane.showMessageDialog(null,"You have not saved this staff member to the database. First Save details");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_delete_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_staffActionPerformed
          
        txt_status.setText("");
        if(checkempty()){
        JOptionPane.showMessageDialog(null, "No Staff member Selected");
        txt_staff_search.requestFocusInWindow();}
   else{
       int choice=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this staff member ","Delete Staff member",JOptionPane.YES_NO_OPTION);
       if(choice==0){
        con = mysqlconnect.connectDB();
        try{
            String sql = "delete from staff_member  where s_nic=?";
            pst = con.prepareStatement(sql);
            pst.setString(1,txt_nic.getText());
       
            pst.execute();
            JOptionPane.showMessageDialog(null,"Staff member  Deleted");
            btn_staff_clear.doClick();
            txt_status.setText("One staff member deleted");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data not deleted");

        }finally{
            closeall();
        }
   }
   }
    }//GEN-LAST:event_btn_delete_staffActionPerformed

    private void btn_update_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_staffActionPerformed
         
        txt_status.setText("");
        if(checkempty()){
        JOptionPane.showMessageDialog(null, "No Staff member Selected");
        txt_staff_search.requestFocusInWindow();}
       else{
            check_change_academic();
           int choice = JOptionPane.showConfirmDialog(null,"Are you sure you want to change details","Update Staff member Details",JOptionPane.YES_NO_OPTION);
           if(choice==0){
        con = mysqlconnect.connectDB();
       try{
           String sql = "update staff_member set s_name=? , s_epf=?, s_district = ?, s_center = ?,s_ac_status=?, s_type=?, s_tel=?,s_email= ?,gender = ?  where s_nic=?";
           pst = con.prepareStatement(sql);
           pst.setString(1, txt_name.getText());
           pst.setString(2, txt_epf.getText());
           pst.setString(3,cmb_district.getSelectedItem().toString());
           pst.setString(4, cmb_center.getSelectedItem().toString());
           pst.setString(5, cmb_aca.getSelectedItem().toString());
           pst.setString(6, cmb_stype.getSelectedItem().toString());
           pst.setString(7, txt_tel.getText());
           pst.setString(8,txt_email.getText());
        
           pst.setString(9, gender);
           pst.setString(10, txt_nic.getText());
           
           pst.execute();
           JOptionPane.showMessageDialog(null,"Details Updated");
           txt_status.append("\n"+ txt_nic.getText()+ " Details Updated");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Details not updated");
           txt_status.append("\n"+ txt_nic.getText()+ " Details not Updated");
           }
       try{
           File file = new File(filename);
           FileInputStream fis = new FileInputStream(file);
           byte[] image = new byte[(int) file.length()];
           fis.read(image);
           String sql = "update staff_member set image = ? where s_nic=?";
           pst = con.prepareStatement(sql);
           pst.setBytes(1, image);
           pst.setString(2, txt_nic.getText());
           pst.executeUpdate();
           pst.close();
//           JOptionPane.showMessageDialog(null,"Image Updated");
           txt_status.append("\n Image updated");     
       }catch(Exception e){
//           JOptionPane.showMessageDialog(null,"Image not updated");
           txt_status.append("\n Image  not updated");
       }
       
       
       
       
       finally{
           closeall();
           
       }
       if(cmb_aca.getSelectedIndex()==0){
    update_academic();
}
       
      if(change_academic==true){
          if(cmb_aca.getSelectedItem().equals("Academic")){
              reinsert_academic();
          }else{
              reinsert_non_academic();
          }
      }
       
       
       
       
           }
       }
    }//GEN-LAST:event_btn_update_staffActionPerformed

    private void btn_edit_course_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_course_listActionPerformed
        frm_add_course temp_add_course = new frm_add_course();
        temp_add_course.setVisible(true);
    }//GEN-LAST:event_btn_edit_course_listActionPerformed

    private void txt_nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nicKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nicKeyReleased

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
       gender = "Male";
       r_male.setSelected(true);
       r_female.setSelected(false);
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
      gender = "Female";
      r_female.setSelected(true);
      r_male.setSelected(false);
    }//GEN-LAST:event_r_femaleActionPerformed

    private void btn_attach_staff_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attach_staff_imageActionPerformed
       JFileChooser chooser = new JFileChooser();
       chooser.showOpenDialog(null);
       File f = chooser.getSelectedFile();
       filename = f.getAbsolutePath();
       ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(),img.getHeight(), Image.SCALE_DEFAULT));
       img.setIcon(imageicon);
       try{
           File image = new File(filename);
           FileInputStream fix = new FileInputStream(image);
           ByteArrayOutputStream bos = new ByteArrayOutputStream();
           byte [] buf = new byte[1024];
           
           for(int number; (number = fix.read(buf))!=-1; ){
               bos.write(buf, 0, number);
           }
           person_image = bos.toByteArray();
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Image can not be attached");
       }
       
    }//GEN-LAST:event_btn_attach_staff_imageActionPerformed

    private void txt_staff_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_staff_searchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_staff_searchKeyPressed

    private void btn_staff_remove_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_staff_remove_imageActionPerformed
       img.setIcon(null);
       con = mysqlconnect.connectDB();
       try{
           String sql = "update staff_member set image = null where s_nic = ?";
           pst = con.prepareStatement(sql);
           
           pst.setString(1,txt_nic.getText());
           pst.execute();
           JOptionPane.showMessageDialog(null, "Image Removed");
           txt_status.setText("");
           txt_status.setText(txt_nic.getText()+ " Image removed");
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Image can not be removed");
       }
       finally{
           closeall();
       }
   
    }//GEN-LAST:event_btn_staff_remove_imageActionPerformed

    private void btn_refresh_course_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_course_listActionPerformed
        cmb_course.removeAllItems();
        
        add_course_list_staff();
    }//GEN-LAST:event_btn_refresh_course_listActionPerformed

    private void txt_telFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telFocusLost
        if(txt_tel.getText().length()==10  && txt_tel.getText().matches("[0-9]+")){
        
    }else{
                JOptionPane.showMessageDialog(null,"Invalid Phone Number !");
            
        }
    }//GEN-LAST:event_txt_telFocusLost

    private void txt_epfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_epfFocusLost
        if(txt_epf.getText().matches("[0-9]+")){
            
        }else{
            JOptionPane.showMessageDialog(null, "Invalid EPF Number !");
        }
    }//GEN-LAST:event_txt_epfFocusLost

    private void cmb_districtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_districtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_districtActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed
public void  reinsert_academic(){
        con=mysqlconnect.connectDB();
     try{
         String sql = "delete from  non_academic where s_nic=?";
         pst = con.prepareStatement(sql);
         pst.setString(1,txt_nic.getText());
         
         pst.execute();
//         JOptionPane.showMessageDialog(null,"Deleted from non academic list");
         txt_status.append("\n Deleted from non academic list");
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
     finally{
         closeall();
     }
     addacademic();
    
}
public void reinsert_non_academic(){
            con=mysqlconnect.connectDB();
     try{
         String sql = "delete from  academic where s_nic=?";
         pst = con.prepareStatement(sql);
         pst.setString(1,txt_nic.getText());
         
         pst.execute();
//         JOptionPane.showMessageDialog(null,"Deleted from on academic list");
         txt_status.append("\n Deleted from  academic list");
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
     finally{
         closeall();
     }
     nonacademic();
    
}
    public void closeall(){
try{
    
    rs.close();
    pst.close();
    con.close();
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
}
 public void addacademic(){
     con=mysqlconnect.connectDB();
     try{
         String sql = "insert into academic (s_nic,ins_course) values(?,?)";
         pst = con.prepareStatement(sql);
         pst.setString(1,txt_nic.getText());
         pst.setString(2,cmb_course.getSelectedItem().toString());
         pst.execute();
//         JOptionPane.showMessageDialog(null,"Academic added");
         txt_status.append(" Added  to academic section \n");
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Details can not be added to Academic section ");
     }
     finally{
         closeall();
     }
     
 }
 public void nonacademic(){
          con=mysqlconnect.connectDB();
     try{
         String sql = "insert into non_academic (s_nic) values(?)";
         pst = con.prepareStatement(sql);
         pst.setString(1,txt_nic.getText());
        
         pst.execute();
         txt_status.append(" Added  to Non academic section \n");
         
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Details can not be  added to Non-Academic section ");
     }
     finally{
         closeall();
     }
 }
     public void update_academic(){
              con=mysqlconnect.connectDB();
     try{
         String sql = "update academic set ins_course = ? where academic.s_nic = ?";
         pst = con.prepareStatement(sql);
         pst.setString(1,cmb_course.getSelectedItem().toString());
         pst.setString(2,txt_nic.getText());
         pst.execute();
//         JOptionPane.showMessageDialog(null,"Academic updated");
         txt_status.append("\n Course updated");
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
     finally{
         closeall();
     }
         
         
     }
     public void check_change_academic(){
         con = mysqlconnect.connectDB();
         String sql = "select s_ac_status from staff_member where s_nic=?";
         try{
    pst = con.prepareStatement(sql);
    pst.setString(1,txt_nic.getText());
    
    rs = pst.executeQuery();
    String academic_stat = cmb_aca.getSelectedItem().toString();
//    String s_ac_status= rs.getString("s_ac_status");
    if(rs.next() && academic_stat.equals(rs.getString("s_ac_status"))){
//        JOptionPane.showMessageDialog(null, "No change");
        txt_status.setText("Academic status has not been changed");
        change_academic = false;
        
      
       
    }
    else{
//        JOptionPane.showMessageDialog(null, " Change has happened ");
        txt_status.setText("Academic status has  been changed");
        
        change_academic = true;
        
       
    }
}
    catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
          
            }
         finally{
             closeall();
         }
        
       
         
     }
     
 
 public boolean checkempty(){
     if(txt_nic.getText().isEmpty()==true || txt_name.getText().isEmpty() == true){
       return true;  
     }else{
         return false;
     }
 }
 public boolean check_nic(){
     con = mysqlconnect.connectDB();
     String sql = "select s_nic from staff_member where s_nic=?";
     try{
         pst = con.prepareStatement(sql);
         pst.setString(1,txt_nic.getText());
         rs = pst.executeQuery();
         if(rs.next()){
             return true;
         }else{
             return false;
         }
         
     }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
     finally{
         closeall();
     }
        return false;
             
     
 }
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_centre;
    private javax.swing.JButton btn_addstaff;
    private javax.swing.JButton btn_attach_staff_image;
    private javax.swing.JButton btn_delete_staff;
    private javax.swing.JButton btn_edit_course_list;
    private javax.swing.JButton btn_refresh_course_list;
    private javax.swing.JButton btn_staff_clear;
    private javax.swing.JButton btn_staff_remove_image;
    private javax.swing.JButton btn_update_staff;
    private javax.swing.JComboBox<String> cmb_aca;
    private javax.swing.JComboBox<String> cmb_center;
    public static javax.swing.JComboBox<String> cmb_course;
    public static javax.swing.JComboBox<String> cmb_district;
    private javax.swing.JComboBox<String> cmb_stype;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_email;
    public static javax.swing.JTextField txt_epf;
    public static javax.swing.JTextField txt_name;
    public static javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_staff_search;
    private javax.swing.JTextArea txt_status;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
private String gender;
private ImageIcon format = null;
String filename = null;
byte[] person_image = null;




}
