//
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
 

package lastproject;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashSet;
import javax.swing.*;
/**
 *
 * @author SHIRAF
 */
public class panel_user extends javax.swing.JPanel {
    Connection con = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   
    /**
     * Creates new form panel_user
     */
    public panel_user() {
        initComponents();
        addusers();
        cmb_newuser.setSelectedItem("");
        
        
        
        if(saveuser.cuser.equals("admin")){
       btn_adduser.setEnabled(true);
       btn_changeuser.setEnabled(true);
       btn_deleteuser.setEnabled(true);
       btn_userclear.setEnabled(true);
       txt_newpass.setEnabled(true);
       txt_user_retype_pass.setEnabled(true);
       cmb_newuser.setEnabled(true);
       
        }
      
        cmb_newuser.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
             if(e.getStateChange()==ItemEvent.SELECTED){
//                 if(cmb_newuser.getSelectedItem().toString().isEmpty()==false)
                 showpass();
                 
             }   
            }
        });

    }
    public void showpass(){
        con=mysqlconnect.connectDB();
        try{
            String sql = "select * from login where username = ?";
            pst=con.prepareStatement(sql);
            pst.setString(1,cmb_newuser.getSelectedItem().toString());
            rs = pst.executeQuery();
            if(rs.next()){
            String pass = rs.getString("password");
            txt_newpass.setText(pass);}
            else{
//                JOptionPane.showMessageDialog(null,"No Records found!");
//                txt_newpass.setText("");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }
                
    
    public void addusers(){
        con = mysqlconnect.connectDB();
        try{
            String sql = "select * from login";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String pat = rs.getString("username");
                cmb_newuser.addItem(pat);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                    
                    }
        finally{
            try{
                
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
            
            
        }
    
    
   
    

    /**
     * This method is called from within the constructor to initialize the form
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_adduser = new javax.swing.JButton();
        btn_userclear = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_deleteuser = new javax.swing.JButton();
        btn_changeuser = new javax.swing.JButton();
        cmb_newuser = new javax.swing.JComboBox();
        txt_newpass = new javax.swing.JPasswordField();
        txt_user_retype_pass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel8.setText("Password");

        btn_adduser.setBackground(new java.awt.Color(153, 153, 255));
        btn_adduser.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_adduser.setText("Create new User");
        btn_adduser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adduser.setEnabled(false);
        btn_adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adduserActionPerformed(evt);
            }
        });
        btn_adduser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_adduserKeyPressed(evt);
            }
        });

        btn_userclear.setBackground(new java.awt.Color(153, 153, 255));
        btn_userclear.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_userclear.setText("Clear");
        btn_userclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_userclear.setEnabled(false);
        btn_userclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userclearActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel15.setText("User Accounts");

        btn_deleteuser.setBackground(new java.awt.Color(153, 153, 255));
        btn_deleteuser.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_deleteuser.setText("Delete User");
        btn_deleteuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteuser.setEnabled(false);
        btn_deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteuserActionPerformed(evt);
            }
        });

        btn_changeuser.setBackground(new java.awt.Color(153, 153, 255));
        btn_changeuser.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_changeuser.setText("Change Password");
        btn_changeuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_changeuser.setEnabled(false);
        btn_changeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeuserActionPerformed(evt);
            }
        });

        cmb_newuser.setEditable(true);
        cmb_newuser.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        cmb_newuser.setEnabled(false);
        cmb_newuser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_newuserItemStateChanged(evt);
            }
        });
        cmb_newuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_newuserActionPerformed(evt);
            }
        });
        cmb_newuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb_newuserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb_newuserKeyReleased(evt);
            }
        });

        txt_newpass.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        txt_newpass.setEnabled(false);

        txt_user_retype_pass.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        txt_user_retype_pass.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel9.setText("Retype Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cmb_newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txt_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_userclear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_changeuser))
                                .addContainerGap(128, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_user_retype_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(btn_deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_changeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user_retype_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_userclear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adduserActionPerformed
        if( cmb_newuser.getSelectedItem().toString().isEmpty()==true || txt_newpass.getText().isEmpty()== true ){
                        JOptionPane.showMessageDialog(null, "You have not entered Username or Password");
            cmb_newuser.requestFocusInWindow();
            }else if (txt_newpass.getText().equals(txt_user_retype_pass.getText())==false){
                  JOptionPane.showMessageDialog(null, "Retyped password does not match");  
                    
        }
      
        else{
            con = mysqlconnect.connectDB();
            try{
                String sql = "insert into login(username,password) values(?,?)";
                pst = con.prepareStatement(sql);
                pst.setString(1,cmb_newuser.getSelectedItem().toString());
                pst.setString(2,txt_newpass.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, " User Account Added");
                 txt_newpass.setText("");
                 txt_user_retype_pass.setText("");
           cmb_newuser.setSelectedItem("");
           

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "User Account can not be added");
                 txt_newpass.setText("");
           cmb_newuser.setSelectedItem("");
            }
        }
        }
        {
    }//GEN-LAST:event_btn_adduserActionPerformed

    private void btn_userclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userclearActionPerformed
        
        txt_newpass.setText("");
        txt_user_retype_pass.setText("");
        cmb_newuser.setSelectedItem("");
        cmb_newuser.requestFocusInWindow();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_userclearActionPerformed

    private void btn_adduserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_adduserKeyPressed
btn_adduser.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_adduserKeyPressed

    private void cmb_newuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_newuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_newuserActionPerformed

    private void cmb_newuserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_newuserItemStateChanged


    }//GEN-LAST:event_cmb_newuserItemStateChanged

    private void btn_deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteuserActionPerformed
       if(cmb_newuser.getSelectedItem().toString().isEmpty()==true){
           JOptionPane.showMessageDialog(null,"No User Account selected");
       }else{
           int choice = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete the user","Delete user",JOptionPane.YES_NO_OPTION );
           if(choice==0){
        con = mysqlconnect.connectDB();
       try{
           String sql = "delete from login where username= ?";
           pst = con.prepareStatement(sql);
           pst.setString(1,cmb_newuser.getSelectedItem().toString());
           pst.execute();
           JOptionPane.showMessageDialog(null,"User Account Deleted");
           txt_newpass.setText("");
           txt_user_retype_pass.setText("");
           cmb_newuser.setSelectedItem("");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "User Account can not be deleted");
            txt_newpass.setText("");
            txt_user_retype_pass.setText("");
           cmb_newuser.setSelectedItem("");
       }
       finally{
           try{
               rs.close();
               pst.close();
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
       }
       }
       }
    }//GEN-LAST:event_btn_deleteuserActionPerformed

    private void btn_changeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeuserActionPerformed
      if(cmb_newuser.getSelectedItem().toString().isEmpty()==true){
           JOptionPane.showMessageDialog(null,"No User Account selected");
      } else if(txt_newpass.getText().equals(txt_user_retype_pass.getText())==false){
                  JOptionPane.showMessageDialog(null, "Retyped password does not match");  
                    
        }
       else{
           int choice = JOptionPane.showConfirmDialog(null,"Are you sure you want to change the password","Change Password",JOptionPane.YES_NO_OPTION );
           if(choice==0){
        con = mysqlconnect.connectDB();
       try{
           String sql = "update login set password=? where username=?";
           pst = con.prepareStatement(sql);
           pst.setString(1,txt_newpass.getText());
           pst.setString(2,cmb_newuser.getSelectedItem().toString());
           pst.execute();
           JOptionPane.showMessageDialog(null,"Password changed");
           txt_newpass.setText("");
           cmb_newuser.setSelectedItem("");
           txt_user_retype_pass.setText("");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Password can not be changed");
            txt_newpass.setText("");
            txt_user_retype_pass.setText("");
           cmb_newuser.setSelectedItem("");
           
       }
       finally{
           try{
               rs.close();
               pst.close();
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
       }
       }
       }
    }//GEN-LAST:event_btn_changeuserActionPerformed

    private void cmb_newuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_newuserKeyPressed
       
    }//GEN-LAST:event_cmb_newuserKeyPressed

    private void cmb_newuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_newuserKeyReleased
     
    }//GEN-LAST:event_cmb_newuserKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adduser;
    private javax.swing.JButton btn_changeuser;
    private javax.swing.JButton btn_deleteuser;
    private javax.swing.JButton btn_userclear;
    private javax.swing.JComboBox cmb_newuser;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txt_newpass;
    private javax.swing.JPasswordField txt_user_retype_pass;
    // End of variables declaration//GEN-END:variables
}
