/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lastproject;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
//import java.sql.Date;

/**
 *
 * @author SHIRAF
 */
public class select_train_program extends javax.swing.JFrame {
    Connection con = null;
   PreparedStatement pst = null;
   ResultSet rs = null;

    /**
     * Creates new form select_train_program
     */
    public select_train_program() {
        initComponents();
        
        addd_details_nic();
        fill_src_table();
        update_completed_table();
        seticon();
    }
    public void fill_src_table(){
               con=mysqlconnect.connectDB();
     try{
         
String sql = "SELECT training_programme.p_id as Programme_ID, training_programme.p_name as Programme_Name FROM training_programme WHERE training_programme.p_id NOT IN ( SELECT participation.p_id FROM participation WHERE participation.s_nic = ? )";


         pst=con.prepareStatement(sql);
         pst.setString(1,txt_select_train_nic.getText());
        
         rs= pst.executeQuery();
         tbl_select_train_src.setModel(DbUtils.resultSetToTableModel(rs));
         
         
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
     finally{
     closeall();
     }
        
    }
    public void addd_details_nic(){
       txt_select_train_nic.setText(panel_staff.txt_nic.getText());
       txt_select_train_name.setText(panel_staff.txt_name.getText());
       txt_select_train_epf.setText(panel_staff.txt_epf.getText());
      
    }
    public void update_completed_table(){
                     con=mysqlconnect.connectDB();
     try{
         String sql = "select participation.p_id as Programmme_ID,training_programme.p_name as Programme_Name,Cast(participation.start_date as char(10) )as Started_Date ,Cast(participation.end_date as char(10)) as Ended_Date  from training_programme,participation where participation.s_nic=? and participation.p_id = training_programme.p_id ";
         pst=con.prepareStatement(sql);
         pst.setString(1,txt_select_train_nic.getText());
         rs= pst.executeQuery();
         tbl_select_train_completed.setModel(DbUtils.resultSetToTableModel(rs));
         
         
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
     finally{
     closeall();
     }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_select_train_nic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_select_train_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_select_train_epf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_select_train_src = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_select_train_completed = new javax.swing.JTable();
        btn_transfer_rows = new javax.swing.JButton();
        btn_insert_completed_train = new javax.swing.JButton();
        btn_transfer_reset = new javax.swing.JButton();
        btn_delete_completed_train = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Record Management System Of ASD");
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("Select Training Programs");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel2.setText("NIC No");

        txt_select_train_nic.setEditable(false);
        txt_select_train_nic.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel3.setText("Name");

        txt_select_train_name.setEditable(false);
        txt_select_train_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel4.setText("EPF");

        txt_select_train_epf.setEditable(false);
        txt_select_train_epf.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N

        tbl_select_train_src.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Programme ID", "Programme Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_select_train_src.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbl_select_train_src);

        tbl_select_train_completed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Programme ID", "Programme Name", "Start Date", "End Date"
            }
        ));
        jScrollPane2.setViewportView(tbl_select_train_completed);

        btn_transfer_rows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lastproject/images/icons8_Double_Right_25px.png"))); // NOI18N
        btn_transfer_rows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transfer_rowsActionPerformed(evt);
            }
        });

        btn_insert_completed_train.setBackground(new java.awt.Color(153, 153, 255));
        btn_insert_completed_train.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_insert_completed_train.setText("Save");
        btn_insert_completed_train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insert_completed_trainActionPerformed(evt);
            }
        });

        btn_transfer_reset.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_transfer_reset.setText("Reset");
        btn_transfer_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transfer_resetActionPerformed(evt);
            }
        });

        btn_delete_completed_train.setBackground(new java.awt.Color(153, 153, 255));
        btn_delete_completed_train.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btn_delete_completed_train.setText("Delete");
        btn_delete_completed_train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_completed_trainActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Completed Training Programmes");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Incompleted Training Programmes");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setText("Please enter dates in yyyy-mm-dd format");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lastproject/images/icons8_Cancel_25px_1.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lastproject/images/icons8_Ok_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_select_train_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_select_train_name, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_select_train_epf, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_transfer_reset)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_transfer_rows)
                                        .addGap(9, 9, 9))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_insert_completed_train, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(79, 79, 79)
                                                .addComponent(btn_delete_completed_train, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 29, Short.MAX_VALUE))))))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_select_train_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_select_train_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_select_train_epf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btn_transfer_rows, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_transfer_reset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_insert_completed_train, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_delete_completed_train, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_transfer_rowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transfer_rowsActionPerformed
//       TableModel model1 = tbl_select_train_src.getModel();
       DefaultTableModel model_test = (DefaultTableModel) tbl_select_train_src.getModel();
        int[] indexs = tbl_select_train_src.getSelectedRows();
        Object[] row = new Object[2];
        DefaultTableModel model2 = (DefaultTableModel) tbl_select_train_completed.getModel();
        for(int i = 0;i<indexs.length;i++){
            row[0] = model_test.getValueAt(indexs[i], 0);
             row[1] = model_test.getValueAt(indexs[i], 1);
             model2.addRow(row);
             model_test.removeRow(indexs[i]);
             
             
            
        }
    
        
        
        
        
    }//GEN-LAST:event_btn_transfer_rowsActionPerformed

    private void btn_insert_completed_trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insert_completed_trainActionPerformed
con = mysqlconnect.connectDB();
try{
    int row_count = tbl_select_train_completed.getRowCount();
    String query = "insert ignore into participation (s_nic,p_id,start_date,end_date) values (?,?,?,?)";
    pst = con.prepareStatement(query);
    
    
    
    
    
    for(int r = 0;r<row_count;r++){
        String s_nic = txt_select_train_nic.getText();
    String p_id = (String)tbl_select_train_completed.getValueAt(r, 0);
    String  start_date = (String)(tbl_select_train_completed.getValueAt(r, 2));
    String   end_date = (String)(tbl_select_train_completed.getValueAt(r, 3));
       
    pst.setString(1, s_nic);
    pst.setString(2, p_id);
    pst.setString(3, start_date );
    pst.setString(4, end_date  );
    

    pst.addBatch();
    
    }
    pst.executeBatch();
    JOptionPane.showMessageDialog(null,"Details added");
//    update_completed_table();
    
    
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
finally{
    closeall();
}

    }//GEN-LAST:event_btn_insert_completed_trainActionPerformed

    private void btn_transfer_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transfer_resetActionPerformed
 fill_src_table();
        update_completed_table();       
    }//GEN-LAST:event_btn_transfer_resetActionPerformed

    private void btn_delete_completed_trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_completed_trainActionPerformed
        int choice=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete selected programme from completed list  ","Delete completed programme",JOptionPane.YES_NO_OPTION);  
        if(choice==0){
        con = mysqlconnect.connectDB();
        int row = tbl_select_train_completed.getSelectedRow();
       String table_click = (tbl_select_train_completed.getModel().getValueAt(row,0).toString());
       String s_nic = txt_select_train_nic.getText();
       try{
           String sql = "delete  from participation  where p_id = '"+table_click+"'and s_nic ='"+s_nic+"'" ;
           pst = con.prepareStatement(sql);
           pst.execute();
           update_completed_table();
           fill_src_table();
           
           
                    
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       finally{
           closeall();
       }
        }
    }//GEN-LAST:event_btn_delete_completed_trainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_train_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_train_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_train_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_train_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_train_program().setVisible(true);
            }
        });
    }
    public void closeall(){
    try{
         rs.close();
    pst.close();
    con.close();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);

            }
            
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_completed_train;
    private javax.swing.JButton btn_insert_completed_train;
    private javax.swing.JButton btn_transfer_reset;
    private javax.swing.JButton btn_transfer_rows;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_select_train_completed;
    private javax.swing.JTable tbl_select_train_src;
    private javax.swing.JTextField txt_select_train_epf;
    private javax.swing.JTextField txt_select_train_name;
    private javax.swing.JTextField txt_select_train_nic;
    // End of variables declaration//GEN-END:variables
 public void seticon(){
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_Course_48px_1.png")));
 }
}
